////date:07/06/22
//program to demonstrate to open(ALL) multiple window
package webdriver_programs;//program to demonstrate getWindowHandle and getWindowHandles

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class p5 {

	public static void main(String[] args) {
			System.setProperty("webdriver.chrome.driver","./drivers/chromedriver.exe");
			WebDriver driver=new ChromeDriver();
			driver.get("https://demoqa.com/browser-windows");
			
			//clicks on new window for 3times
			driver.findElement(By.id("windowButton")).click();
			driver.findElement(By.id("windowButton")).click();
			driver.findElement(By.id("windowButton")).click();
		
					String mainWindow = driver.getWindowHandle();// returns the unique reference of the main window generated by selenium

					Set<String> allWindows = driver.getWindowHandles();// returns the unique reference of the all window generated by selenium
					
					System.out.println(mainWindow);
					System.out.println(allWindows);
					
					System.out.println(allWindows.getClass().getName());// returns the type of set
	}

}
